### ISSUE TITLE
Multi-Tenant startup - TenantNotFoundException (gorm-graphql 1.0.3-BUILD-SNAPSHOT/Grails 4.0.0)

### ISSUE THREAD

**Issue by ianibo** [grails/gorm-graphql#24]
Hi

Currently looking to see if this plugin might be able to help in a multi-tenant (database schema-per-tenant) microservice component that we would like to transition to graphql.

I'm having a problem using the plugin in our component because the example tenant app uses the SystemPropertyTenantResolver - which means that the example project has a tenant ID in it's hand at application startup time. This in turn means that when the doWithSpring block in GormGraphqlGrailsPlugin.groovy executes the ultimate call to findStaticApi in GormEnhancer can work as in a single tenant environment.

However, in a real multi-tenant scenario (We're using schema-per-tenant, which I suspect might give us a different problem) systems will usually derive the tenant from some property of the request - and as such, the tenant identifier is not available at spring-controlled component init time. The plugin currently fails with the stack-trace at the bottom of this issue when started with a non-test tenant resolver.

I'd like to help resolve this, but could use some advice on the best way forward - I was wondering about a defer option which would delay the call to Schema.generate until the first request came along? Appreciate thats not great for pre-caching the graphql state. Another feature of our environment is that when the app starts we don't have any tenants, although we do have hooks to call functions after new tenants are created (after liquibase migrations have run to create the structure for the tenant). Similarly, I'm not clear yet if all the cached data fetchers will be a problem for us in the (database) Schema-per-tenant environment, and if we really need a (GraphQL) Schema-per-tenant also?

Any thoughts or suggestions? As I said - really happy to try and work through this but need some guidance on where to start.

Cheers.

stacktrace follows::
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLSchema': Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'generate' threw exception; nested exception is org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at mod.directory.Application.main(Application.groovy:8)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'generate' threw exception; nested exception is org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 23 common frames omitted
Caused by: org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request
        at com.k_int.okapi.OkapiTenantResolver.resolveTenantIdentifier(OkapiTenantResolver.groovy:65)
        at grails.gorm.multitenancy.Tenants.currentId(Tenants.groovy:73)
        at org.grails.datastore.gorm.GormEnhancer.findTenantId(GormEnhancer.groovy:270)
        at org.grails.datastore.gorm.GormEnhancer.findStaticApi(GormEnhancer.groovy:296)
        at org.grails.gorm.graphql.fetcher.DefaultGormDataFetcher.<init>(DefaultGormDataFetcher.groovy:51)
        at org.grails.gorm.graphql.fetcher.DefaultGormDataFetcher.<init>(DefaultGormDataFetcher.groovy:44)
        at org.grails.gorm.graphql.fetcher.impl.SingleEntityDataFetcher.<init>(SingleEntityDataFetcher.groovy)
        at org.grails.gorm.graphql.Schema.generate(Schema.groovy:266)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 24 common frames omitted
```

**Comment by armsargis** [comment]
Hi, do you have example project I can try to check issue.

**Comment by ianibo** [comment]
Hey @armsargis Sorry this has taken a couple of days to sort - but yes : Please see

https://github.com/ianibo/grails4-schema-per-tenant-test/tree/mt_graphql

The master branch is a trivial grails 4 schema-per-tenant example which works (Has an integration test that establishes two tenants, creates their schemas, and adds some data to the separate tenants. It's not super pretty, but it works in an in-memory H2 DB) running with grails test-app all tests pass.

The branch mt_graphql simply adds the graphql plugin dependency and sets graphql=true on the one domain class (Widget). Running grails test-app now immediately throws the exception as seen belowe

    sptt.LifecycleSpec > test tenant creation FAILED
        java.lang.IllegalStateException
           Caused by: org.springframework.beans.factory.BeanCreationException
                Caused by: org.springframework.beans.factory.BeanCreationException
                    Caused by: org.springframework.beans.BeanInstantiationException
                        Caused by: org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException

Hope this helps - please feel free to shout out if this isn't clear or there is more I can do - would love to have this working in a schema-per-tenant setup.

Ian.

**Comment by ianibo** [comment]
Updated the title to be grails 4 related now, with the attached example test project.

**Comment by ianibo** [comment]
As a note with slightly more specific information  - the problem starts at line 266 of schema.groovy (https://github.com/grails/gorm-graphql/blob/aabd1ca5bf904a9d6298fe63b6dbf427fbaab506/core/src/main/groovy/org/grails/gorm/graphql/Schema.groovy). This in turn calls DefaultGormDataFetcher which calls  org.grails.datastore.gorm.GormEnhancer.findStaticApi - and ultimately in a multi-tenant setup this will fail if the declared tenant resolver is unable to resolve a tenant for the current request.

**Comment by ianibo** [comment]
Upgraded the test project to grails 4.0.1 same problem.

**Comment by ianibo** [comment]
Digging into this - the test harness for 4.0.1 fails in an unexpected way that looks related to the multi tenant setup in 4.0.1- before it gets to gorm-graphql. I believe the underlying issue is still there, but probably not worth spending time on until we can get basic schema-per-tenant working in 4.0.1.
