### ISSUE TITLE
ValidationConfigurationException: Constraint [unique] is not supported

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-graphql#27]
**Description**

I have an application which use Neo4j and I want to add the GraphQL plugin.

There is a shared constraint which has a unique constraint.

```
grails.gorm.default.constraints = {
    uniqueName nullable: false, blank: false, unique: true
}
```

Also, there are domain classes which use that shared constraint.
```
class Speaker {

    static mapWith = "neo4j"
    static graphql = true

    String name

    static constraints = {
        name shared: 'uniqueName'
    }

}
```

**Problem**

When I try to run the app I have an exception.

```
Caused by: grails.gorm.validation.exceptions.ValidationConfigurationException: Constraint [unique] is not supported for property [name] of class [class gormgraphql.Speaker] with type [class java.lang.String]
        at grails.gorm.validation.DefaultConstrainedProperty.applyConstraint(DefaultConstrainedProperty.groovy:665)
        at org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.applySharedConstraints(DefaultConstraintEvaluator.java:198)
        at org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.evaluate(DefaultConstraintEvaluator.java:176)
        at org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.evaluate(DefaultConstraintEvaluator.java:80)
        at org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator.evaluate(DefaultConstraintEvaluator.java:75)
        at grails.gorm.validation.PersistentEntityValidator.<init>(PersistentEntityValidator.groovy:51)
        at org.grails.datastore.gorm.validation.constraints.registry.DefaultValidatorRegistry.getValidator(DefaultValidatorRegistry.groovy:68)
        at org.grails.datastore.mapping.model.AbstractMappingContext.getEntityValidator(AbstractMappingContext.java:214)
        at org.grails.gorm.graphql.entity.property.impl.PersistentGraphQLProperty.<init>(PersistentGraphQLProperty.groovy:75)
        at org.grails.gorm.graphql.entity.property.manager.DefaultGraphQLDomainPropertyManager$Builder.getProperties(DefaultGraphQLDomainPropertyManager.groovy:125)
        at org.grails.gorm.graphql.entity.property.manager.DefaultGraphQLDomainPropertyManager$Builder.getProperties(DefaultGraphQLDomainPropertyManager.groovy:87)
        at org.grails.gorm.graphql.types.output.AbstractObjectTypeBuilder.build(AbstractObjectTypeBuilder.groovy:75)
        at org.grails.gorm.graphql.types.DefaultGraphQLTypeManager.getQueryType(DefaultGraphQLTypeManager.groovy:215)
        at org.grails.gorm.graphql.Schema.generate(Schema.groovy:257)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 36 common frames omitted
```

**Reproduce the error**

To reproduce the error:

- Download the project from the repository: https://github.com/AmaliaMV/graphql-shared-unique
- Run the project

The versions, I am using, are:

```
grailsVersion=3.3.10
gormVersion=6.1.12.RELEASE
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Aditional notes**
This error does not happen when the hibernate plugin is using. You can check this on 'hiberante' branch.

**Comment by puneetbehl** [comment]
This is happening because there is no `UniqueContraint` in the `DefaultConstraintRegistry`. It works with Hibernate as it is added in the [HibernateDatastore](https://github.com/grails/gorm-hibernate5/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/HibernateDatastore.java#L400)

**Comment by puneetbehl** [comment]
Nvm, I am sorry for the wrong information. It seems to be added for Neo4jDatastore as well, let me take another looks to see what's happening with Neo4j.
