### ISSUE TITLE
Circular association intermittently fails schema generation

### ISSUE THREAD

**Issue by jamesdh** [grails/gorm-graphql#36]
Related to #7 

When using a circular association (in my example via one-to-many association), schema generation will fail ~50% of the time on startup: 

```groovy
class User {
    Address address
    static constraints = {
        address nullable: true
    }
    static graphic = true
}

class Address {
    Set<User> owners
    static hasMany = [
        owners: User
    ]
}
```

results in...

```java
Caused by: graphql.AssertException: type Address not found in schema
	at graphql.Assert.assertNotNull(Assert.java:13)
	at graphql.schema.GraphQLTypeResolvingVisitor.visitGraphQLTypeReference(GraphQLTypeResolvingVisitor.java:42)
	at graphql.schema.GraphQLTypeReference.accept(GraphQLTypeReference.java:45)
	at graphql.schema.TypeTraverser$TraverserDelegateVisitor.enter(TypeTraverser.java:73)
	at graphql.util.Traverser.traverse(Traverser.java:106)
	at graphql.schema.TypeTraverser.doTraverse(TypeTraverser.java:60)
	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:52)
	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:40)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:106)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:341)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:314)
	at org.grails.gorm.graphql.Schema.generate(Schema.groovy:446)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

I've include a full project reproducing this at https://github.com/jamesdh/gorm-graphql-bug. Either running the app or running integration tests should reproduce it ~50% of the time.

**Comment by jamesdh** [comment]
Ok, this appears to be related to #37. If I allow an operation on the `Address` domain, then schema generations never fails.
